name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install depeendencies
      run: sudo apt-get install gcc-arm-none-eabi
    - name: make
      run: cd PiHat-Firmware && make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
